import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import gsap from 'gsap'
import { useEffect } from 'react'

const Home = () => {
	useEffect(() => {
		console.log('Hey mounted!')

		gsap.set('#title, #title a', { x: -100, y: -100, color: 'transparent' })
		gsap.to('#title', {
			x: 0,
			y: 0,
			opacity: 1,
			color: 'black',
			duration: 1, // seconds
			delay: 0.5,
			ease: 'power1.inOut',
		})

		gsap.to('#title a', {
			opacity: 1,
			color: '#e01a1a', // camelCase
			duration: 2, // seconds
			delay: 0.5,
			ease: 'power1.inOut',
		})
	}, [])

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next + GSAP App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 id={`title`} style={{ opacity: 0 }} className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	)
}

export default Home
